---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: ssh
      ansible_user: $SSH_USER  
      ansible_ssh_private_key_file: $HOME/testing-ansible.pem
platforms:
  - name: $SSH_HOST

verifier:
  name: ansible

