---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: ssh
      ansible_user: ec2-user  
      ansible_ssh_private_key_file: /home/upmanyu/Downloads/testing-ansible.pem
platforms:
  - name: $IP1
provisioner:
  name: ansible
verifier:
  name: ansible

