---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: ssh
      ansible_user: $SSH_USER     
platforms:
  - name: $SSH_HOST

verifier:
  name: ansible

