name: Ansibe CI Base
on:
  workflow_call


jobs:
  dynamic-tests:
    runs-on: [rhel8-latest]
    steps:
    - name: Run molecule tests
      run: "cd molecule_testing && molecule --env-file ./molecule/default/ip.yml test" 
